TEST_CASES = [
    # Expected Matches (1-18)
    ("Tyler Bliha", "Tlyer Bilha", True, "Minor transposition and misspelling in both first and last name"),
    ("Al-Hilal", "alhilal", True, "Hyphen and casing differences only"),
    ("Dargulov", "Darguloff", True, "Common phonetic suffix variation (v vs ff)"),
    ("Bob Ellensworth", "Robert Ellensworth", True, "Common nickname vs formal name"),
    ("Mohammed Al Fayed", "Muhammad Alfayed", True, "Spacing and transliteration variance"),
    ("Sarah O'Connor", "Sara Oconnor", True, "Apostrophe removal and vowel simplification"),
    ("Jonathon Smith", "Jonathan Smith", True, "Common spelling variant of first name"),
    ("Abdul Rahman ibn Saleh", "Abdulrahman ibn Saleh", True, "Spacing variation within compound name"),
    ("Al Hassan Al Saud", "Al-Hasan Al Saud", True, "Minor consonant simplification and hyphenation"),
    ("Katherine McDonald", "Catherine Macdonald", True, "Phonetic first name and common Mc/Mac variation"),
    ("Yusuf Al Qasim", "Youssef Alkasim", True, "Transliteration differences in Arabic-derived names"),
    ("Steven Johnson", "Stephen Jonson", True, "Phonetic spelling differences in both names"),
    ("Alexander Petrov", "Aleksandr Petrof", True, "Slavic transliteration and phonetic variation"),
    ("Jean-Luc Picard", "Jean Luc Picard", True, "Hyphen removal"),
    ("Mikhail Gorbachov", "Mikhail Gorbachev", True, "Alternate transliteration endings"),
    ("Elizabeth Turner", "Liz Turner", True, "Common nickname shortening"),
    ("Omar ibn Al Khattab", "Omar Ibn Alkhattab", True, "Case, spacing, and compound-name variance"),
    ("Sean O'Brien", "Shawn Obrien", True, "Phonetic first name and punctuation removal"),
    
    # Expected Non-matches (19-30)
    ("Emanuel Oscar", "Belinda Oscar", False, "Same last name but entirely different first name"),
    ("Michael Thompson", "Michelle Thompson", False, "Similar-looking but distinct first names"),
    ("Ali Hassan", "Hassan Ali", False, "Token order swap changes identity"),
    ("John Smith", "James Smith", False, "Different common first names"),
    ("Abdullah ibn Omar", "Omar ibn Abdullah", False, "Reversal of patronymic meaning"),
    ("Maria Gonzalez", "Mario Gonzalez", False, "Gendered name difference"),
    ("Christopher Nolan", "Christian Nolan", False, "Similar prefix but distinct names"),
    ("Ahmed Al Rashid", "Ahmed Al Rashidi", False, "Different surname root"),
    ("Samantha Lee", "Samuel Lee", False, "Different first name despite shared root"),
    ("Ivan Petrov", "Ilya Petrov", False, "Distinct given names in same cultural group"),
    ("Fatima Zahra", "Zahra Fatima", False, "Name order inversion changes identity"),
    ("William Carter", "Liam Carter", False, "Nickname not universally equivalent without explicit mapping"),
]